package com.boattracking;

import java.time.LocalDateTime;
import java.util.Objects;

/**
 * Represents an alert generated by the boat detection system.
 *
 * <p>An alert encapsulates the type of violation, the boat ID that
 * triggered it, a human‑readable message, and the timestamp of when
 * the violation occurred.</p>
 */
public class Alert {
    private final String boatId;
    private final AlertType type;
    private final String message;
    private final LocalDateTime timestamp;

    /**
     * Constructs a new alert instance.
     *
     * @param boatId    the identifier of the boat responsible for this alert
     * @param type      the type of alert
     * @param message   a descriptive message explaining the alert
     * @param timestamp the time when the alert was generated
     */
    public Alert(String boatId, AlertType type, String message, LocalDateTime timestamp) {
        this.boatId = Objects.requireNonNull(boatId, "boatId must not be null");
        this.type = Objects.requireNonNull(type, "type must not be null");
        this.message = Objects.requireNonNull(message, "message must not be null");
        this.timestamp = Objects.requireNonNull(timestamp, "timestamp must not be null");
    }

    public String getBoatId() {
        return boatId;
    }

    public AlertType getType() {
        return type;
    }

    public String getMessage() {
        return message;
    }

    public LocalDateTime getTimestamp() {
        return timestamp;
    }

    @Override
    public String toString() {
        return "Alert{" +
                "boatId='" + boatId + '\'' +
                ", type=" + type +
                ", message='" + message + '\'' +
                ", timestamp=" + timestamp +
                '}';
    }
}